name: Cypress tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Use Cypress GitHub action to run tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
          NEXT_PUBLIC_FORM: ${{ secrets.NEXT_PUBLIC_FORM }}
        with:
          build: yarn build
          start: yarn start
